Ready repo for crates.io release
enarx/sev-iocuddle pull request #2
Opened 2021-08-17 15:36 UTC by tfanelli-rh

Just about all shared code between `sev` and `snp` are included in the library, I'll make a few small changes before opening for review.

2021-08-17 16:55 UTC, connorkuehl commented
@tfanelli-rh If you haven't already, please also go through the [crates.io packaging checklist](https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate). Just the readiness checks, please don't push the crate to crates.io just yet.

2021-08-17 17:27 UTC, tfanelli-rh commented
> @tfanelli-rh If you haven't already, please also go through the [crates.io packaging checklist](https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate). Just the readiness checks, please don't push the crate to crates.io just yet.

Sure thing.

2021-08-18 17:11 UTC, haraldh requested changes

2021-08-18 17:11 UTC, haraldh commented on src/util.rs
> +    }
again? Didn't you already correct this in https://github.com/enarx/snp/pull/7#discussion_r688317596 ??

2021-08-18 17:58 UTC, tfanelli-rh commented on src/util.rs
> +    }
I had that code from before the update and forgot to reflect the changes. Fixed.

2021-08-18 21:55 UTC, connorkuehl commented
@tfanelli-rh could you configure the Cargo.toml to also include the badges that we see on other Enarx repos like [this](https://github.com/enarx/sev/)? Once they're added to the manifest, regenerating the README with cargo-readme should work.

Aside from that, this looks good to me. Even still, I'd like #3 to merge first so that this PR can rebase against a running CI. Since this PR will likely be the snapshot that is tagged and pushed to crates.io, I thought we'd get the CI merged first so we have a green CI for that tag.

2021-08-19 08:22 UTC, haraldh requested changes
yeah, please rebase to main/master for the CI to run

2021-08-19 14:48 UTC, merged