feat: add KVM_MEMORY_ENCRYPT_REG_REGION and UNREG
enarx/sev-iocuddle pull request #7
Opened 2021-08-21 11:25 UTC by haraldh

Both are specified wrongly as `_IOR` instead of `_IOW`.

2021-08-21 17:07 UTC, npmccallum requested changes

2021-08-21 17:07 UTC, npmccallum commented on src/kvm.rs
> +}
This is not how `iocuddle` works. With this struct, you've made an implicitly unsafe interface.

You need to make a struct that is ABI compatible with what the Linux kernel expects. Then you need to create some constructor for it from safe Rust types. For example, you might want a constructor for `kvm_enc_region` that takes a byte slice (or even a slice of `Page`s). This allows you to get the lifetime correct. See other examples with `PhantomData` to capture the lifetime.

Also, `kvm_enc_region` isn't the right casing for a Rust struct.

2021-08-23 07:59 UTC, haraldh commented on src/kvm.rs
> +}
Oops, sorry... here is a better version following the example of `sev::Launcher::<Started>::update_data()` and `snp::Launcher::<Started>::update_data()`

2021-08-23 12:04 UTC, npmccallum approved these changes

2021-08-23 12:05 UTC, merged